export const testAnticheater = {
  meta: {
    page: 0,
    pages: 6,
    per_page: 5,
    total: 26,
  },
  items: [
    {
      event_id: 129,
      extra: {
        priority: 1,
        avg_pace_event: '4:22',
        event_memberships: 8,
        cheater: false,
        checked: false,
        admin_comment_count: 0,
        too_fast: null,
        too_fast_limit: '',
        manual: false,
        gps: true,
        import_delay: false,
        edited: false,
      },
      standing: {
        distance: 5237.7,
        ratio: 1,
        moving_time: 3647,
        pace: '11:36',
        score: '7.9',
        standing: {
          stood: true,
          status: 'auto_stood',
          message: null,
        },
        criteria: {
          distance: {
            min: 1000,
            aim: 1000,
            fact: 5237.7,
            stood: true,
          },
          pace: {
            min: null,
            max: null,
            aim: null,
            fact: '11:36',
            stood: true,
          },
          has_route: true,
          is_not_manual: true,
          import_delay: {
            min: null,
            aim: null,
            fact: 0,
            stood: true,
          },
          dupe_check: true,
          time_of_day: {
            min: null,
            max: null,
            aim: null,
            fact: '12:31',
            stood: true,
          },
        },
      },
      track: {
        id: 1709569,
        tracker: {
          id: 10857,
          tracker: 'alivebe',
          created_at: '2022-06-10 09:12:23',
          updated_at: '2022-06-10 09:12:23',
          last_sync_time: '2024-02-04 11:45:46',
          last_error_id: null,
          enabled: true,
        },
        user: {
          id: 1697,
          first_name: 'Alexander',
          last_name: 'Ivanov',
          full_name: 'Alexander Ivanov',
          avatar:
            'https://dev2.alivebe.com/thumbnails/user/20230913/818fbf61cc5f7a4a1e0a2f846c90e317_160x160.jpg',
          last_online: '2024-02-04 11:56:50',
          age: 34,
          date_of_birth: '1989-11-07',
          gender: 'm',
          isFriend: false,
          friendRequest: false,
          rating: {
            place: 84,
            points: '308.64',
          },
          awardCount: 0,
          likeCount: 11,
          friendCount: 0,
          location: {
            country: {
              id: 1894,
              code: 'kz',
              name: 'Казахстан',
            },
            city: {
              id: 2079,
              country_id: 1894,
              country_code: 'kz',
              region_id: 2074,
              name: 'Петропавловск',
              full_name: 'Петропавловск, Северо-Казахстанская область, Казахстан',
              has_regions: false,
            },
            city_region: {
              id: 1,
              city_id: 4400,
              city_ad_id: 11,
              name: 'Академический',
              full_name: 'Академический, Юго-Западный',
            },
          },
          sport_category: 'novice',
        },
        sport_id: 5,
        external_id: '98317',
        external_url: '/comment/view/?entityType=TrackerData&entityId=1709569',
        created_at: '2024-01-31 10:33:59',
        updated_at: '2024-02-04 11:45:46',
        start_date: '2024-01-31 09:31:15',
        start_date_local: '2024-01-31 12:31:15',
        start_date_user: '2024-01-31 15:31:15',
        name: 'Ходьба в обед',
        description: '',
        distance: 5237.71,
        steps: 6905,
        total_elevation_gain: 12,
        average_heartrate: 0,
        moving_time: 3647,
        elev_high: 0,
        elev_low: 0,
        route:
          'wwcmJontwD???@A??B?D?J?HAFA@A?CAECCCEEGCG@EBGHGHEDEH]^EAEBEFEHEFEFCFEFBNqF[CEE?CAICGFEHEDCBEDE@GAGEEAGCC?E?GAEAEACCE?E@EBCBECECHF?@c@ImAqA?PANELSBKFGDEBI?MCEBKGEMck@c@g@NO@GDCBE@EBE?EAEAECECCAEACAEAGACCEGCK?M@K@I@K?M@K@KBM@KAK?P??jJopA@A@E@A@I?I?KAMAKAMAMAKAIAI?I?G@I?I@K?K@K@I@I@I@I?K@M@K@K@K@I@K?I@I?KNmB?G?I@I?K?I@M@K@K@I@K?I@E?K@I?M@I@I@K@K@I?K@K@I?I@K@I?K@M?I@I@KBI@G@I@I@I?K@K@I@K@K?I@K@I@I?I@I@K?G@M?K@K@K?I@K@K?I@I?I@I@I@I@K@K?I@K@I@I@K?I@K@G@I@I@GBEBA@A?B????c@_BAK?KAMCI?K?M?KAI?KAIAI?IAKAKAKAOAKoUqyBl@MLAA?GDGDGFE@G@E@G@EBGDGFEDEFEDEBE@EB????@??A???????A??????A@IEECE?E?ECECCAECECE@E?EDIDC@EDGDEDEDE@EJGDG?E@EDEFEDEHALALCJCFCDC@AFAHCLAFAHAFAF?FBLBJ?L?LAPAJCJAFCJCHGPEJ?LANAP?PAL?H?FA@CBCDCHCFAN?N@X?J?L@L?HBJ?J?L?L?JAL@LAJAJAJAJAJ?H?JALAH?JCLALCJAH@I@Gs@dGCPGfB@XwE~i@FLFNDNBL?H@RCJ@J@J@L?JCN@J@JAM?IkBxHAB?EAHXf@[nGBMDBBB@F?J?J?HAJAJAJAJAL?LANAL?LCLAJAJ?LALALAJ?JALAJ?J?LAJAJALALCNAJALALCLAJALAHCFEBEGGAGAEAGAECEEEE',
        is_manual: false,
        end_date_local: '2024-01-31 13:32:02',
        has_dupes: false,
        flagged: false,
        max_pace: '2:05',
        pace: '11:36',
        elapsed_time: 3647,
        max_standing_distance: 5237.71,
        attached: true,
        stood: true,
        standing_status: 'stood',
        image: 'https://dev2.alivebe.com/track/1709569/image/',
        files: [],
        likesCount: 0,
        commentsCount: 0,
        complaintCount: 0,
        liked: false,
        complained: false,
        activity_id: null,
        os: 'android',
      },
      member: {
        joined_at: '2024-01-31 12:37:28',
        qgroup: 1,
        team_id: null,
        results: {
          '1': {
            steps: 1802697,
            distance: 2308353,
            moving_time: 6,
            total_elevation_gain: 46,
          },
          '2': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '3': {
            steps: 0,
            distance: 773921,
            moving_time: 2701,
            total_elevation_gain: 46,
          },
          '4': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '5': {
            steps: 1195675,
            distance: 1133768,
            moving_time: 297218,
            total_elevation_gain: 58,
          },
          '6': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '7': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '8': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '23': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '24': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '25': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '26': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '27': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '28': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '29': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '30': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '31': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '32': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '33': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '34': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '35': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '36': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          score: 9399.6,
          steps: 2998372,
          distance: 4216042,
          moving_time: 299925,
          distanceForQGroup: 15099,
          total_elevation_gain: 150,
        },
      },
    },
    {
      event_id: 131,
      extra: {
        priority: 1,
        avg_pace_event: '15:28',
        event_memberships: 8,
        cheater: false,
        checked: false,
        admin_comment_count: 0,
        too_fast: null,
        too_fast_limit: '',
        manual: false,
        gps: true,
        import_delay: false,
        edited: false,
      },
      standing: {
        distance: 5237.7,
        ratio: 1,
        moving_time: 3647,
        pace: '11:36',
        score: '7.9',
        standing: {
          stood: true,
          status: 'auto_stood',
          message: null,
        },
        criteria: {
          distance: {
            min: null,
            aim: null,
            fact: 5237.7,
            stood: true,
          },
          pace: {
            min: null,
            max: null,
            aim: null,
            fact: '11:36',
            stood: true,
          },
          has_route: true,
          is_not_manual: true,
          import_delay: {
            min: null,
            aim: null,
            fact: 0,
            stood: true,
          },
          dupe_check: true,
          time_of_day: {
            min: null,
            max: null,
            aim: null,
            fact: '12:31',
            stood: true,
          },
        },
      },
      track: {
        id: 1709569,
        tracker: {
          id: 10857,
          tracker: 'alivebe',
          created_at: '2022-06-10 09:12:23',
          updated_at: '2022-06-10 09:12:23',
          last_sync_time: '2024-02-04 11:45:46',
          last_error_id: null,
          enabled: true,
        },
        user: {
          id: 1697,
          first_name: 'Alexander',
          last_name: 'Ivanov',
          full_name: 'Alexander Ivanov',
          avatar:
            'https://dev2.alivebe.com/thumbnails/user/20230913/818fbf61cc5f7a4a1e0a2f846c90e317_160x160.jpg',
          last_online: '2024-02-04 11:56:50',
          age: 34,
          date_of_birth: '1989-11-07',
          gender: 'm',
          isFriend: false,
          friendRequest: false,
          rating: {
            place: 84,
            points: '308.64',
          },
          awardCount: 0,
          likeCount: 11,
          friendCount: 0,
          location: {
            country: {
              id: 1894,
              code: 'kz',
              name: 'Казахстан',
            },
            city: {
              id: 2079,
              country_id: 1894,
              country_code: 'kz',
              region_id: 2074,
              name: 'Петропавловск',
              full_name: 'Петропавловск, Северо-Казахстанская область, Казахстан',
              has_regions: false,
            },
            city_region: {
              id: 1,
              city_id: 4400,
              city_ad_id: 11,
              name: 'Академический',
              full_name: 'Академический, Юго-Западный',
            },
          },
          sport_category: 'novice',
        },
        sport_id: 5,
        external_id: '98317',
        external_url: '/comment/view/?entityType=TrackerData&entityId=1709569',
        created_at: '2024-01-31 10:33:59',
        updated_at: '2024-02-04 11:45:46',
        start_date: '2024-01-31 09:31:15',
        start_date_local: '2024-01-31 12:31:15',
        start_date_user: '2024-01-31 15:31:15',
        name: 'Ходьба в обед',
        description: '',
        distance: 5237.71,
        steps: 6905,
        total_elevation_gain: 12,
        average_heartrate: 0,
        moving_time: 3647,
        elev_high: 0,
        elev_low: 0,
        route:
          'wwcmJontwD???@A??B?D?J?HAFA@A?CAECCCEEGCG@EBGHGHEDEH]^EAEBEFEHEFEFCFEFBNqF[CEE?CAICGFEHEDCBEDE@GAGEEAGCC?E?GAEAEACCE?E@EBCBECECHF?@c@ImAqA?PANELSBKFGDEBI?MCEBKGEMck@c@g@NO@GDCBE@EBE?EAEAECECCAEACAEAGACCEGCK?M@K@I@K?M@K@KBM@KAK?P??jJopA@A@E@A@I?I?KAMAKAMAMAKAIAI?I?G@I?I@K?K@K@I@I@I@I?K@M@K@K@K@I@K?I@I?KNmB?G?I@I?K?I@M@K@K@I@K?I@E?K@I?M@I@I@K@K@I?K@K@I?I@K@I?K@M?I@I@KBI@G@I@I@I?K@K@I@K@K?I@K@I@I?I@I@K?G@M?K@K@K?I@K@K?I@I?I@I@I@I@K@K?I@K@I@I@K?I@K@G@I@I@GBEBA@A?B????c@_BAK?KAMCI?K?M?KAI?KAIAI?IAKAKAKAOAKoUqyBl@MLAA?GDGDGFE@G@E@G@EBGDGFEDEFEDEBE@EB????@??A???????A??????A@IEECE?E?ECECCAECECE@E?EDIDC@EDGDEDEDE@EJGDG?E@EDEFEDEHALALCJCFCDC@AFAHCLAFAHAFAF?FBLBJ?L?LAPAJCJAFCJCHGPEJ?LANAP?PAL?H?FA@CBCDCHCFAN?N@X?J?L@L?HBJ?J?L?L?JAL@LAJAJAJAJAJ?H?JALAH?JCLALCJAH@I@Gs@dGCPGfB@XwE~i@FLFNDNBL?H@RCJ@J@J@L?JCN@J@JAM?IkBxHAB?EAHXf@[nGBMDBBB@F?J?J?HAJAJAJAJAL?LANAL?LCLAJAJ?LALALAJ?JALAJ?J?LAJAJALALCNAJALALCLAJALAHCFEBEGGAGAEAGAECEEEE',
        is_manual: false,
        end_date_local: '2024-01-31 13:32:02',
        has_dupes: false,
        flagged: false,
        max_pace: '2:05',
        pace: '11:36',
        elapsed_time: 3647,
        max_standing_distance: 5237.71,
        attached: true,
        stood: true,
        standing_status: 'stood',
        image: 'https://dev2.alivebe.com/track/1709569/image/',
        files: [],
        likesCount: 0,
        commentsCount: 0,
        complaintCount: 0,
        liked: false,
        complained: false,
        activity_id: null,
        os: 'android',
      },
      member: {
        joined_at: '2024-01-31 12:44:03',
        qgroup: null,
        team_id: 479,
        results: {
          '1': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '2': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '3': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '4': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '5': {
            steps: 125809,
            distance: 228778,
            moving_time: 212408,
            total_elevation_gain: 12,
          },
          '6': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '7': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '8': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '23': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '24': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '25': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '26': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '27': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '28': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '29': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '30': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '31': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '32': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '33': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '34': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '35': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '36': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          score: 343.2,
          steps: 125809,
          distance: 228778,
          moving_time: 212408,
          total_elevation_gain: 12,
        },
      },
    },
    {
      event_id: 64,
      extra: {
        priority: 1,
        avg_pace_event: '14:15',
        event_memberships: 8,
        cheater: false,
        checked: false,
        admin_comment_count: 0,
        too_fast: null,
        too_fast_limit: '',
        manual: false,
        gps: true,
        import_delay: false,
        edited: false,
      },
      standing: {
        distance: 5237.7,
        ratio: 1,
        moving_time: 3647,
        pace: '11:36',
        score: '7.9',
        standing: {
          stood: true,
          status: 'auto_stood',
          message: null,
        },
        criteria: {
          distance: {
            min: 1000,
            aim: 1000,
            fact: 5237.7,
            stood: true,
          },
          pace: {
            min: null,
            max: null,
            aim: null,
            fact: '11:36',
            stood: true,
          },
          has_route: true,
          is_not_manual: true,
          import_delay: {
            min: null,
            aim: null,
            fact: 0,
            stood: true,
          },
          dupe_check: true,
          time_of_day: {
            min: null,
            max: null,
            aim: null,
            fact: '12:31',
            stood: true,
          },
        },
      },
      track: {
        id: 1709569,
        tracker: {
          id: 10857,
          tracker: 'alivebe',
          created_at: '2022-06-10 09:12:23',
          updated_at: '2022-06-10 09:12:23',
          last_sync_time: '2024-02-04 11:45:46',
          last_error_id: null,
          enabled: true,
        },
        user: {
          id: 1697,
          first_name: 'Alexander',
          last_name: 'Ivanov',
          full_name: 'Alexander Ivanov',
          avatar:
            'https://dev2.alivebe.com/thumbnails/user/20230913/818fbf61cc5f7a4a1e0a2f846c90e317_160x160.jpg',
          last_online: '2024-02-04 11:56:50',
          age: 34,
          date_of_birth: '1989-11-07',
          gender: 'm',
          isFriend: false,
          friendRequest: false,
          rating: {
            place: 84,
            points: '308.64',
          },
          awardCount: 0,
          likeCount: 11,
          friendCount: 0,
          location: {
            country: {
              id: 1894,
              code: 'kz',
              name: 'Казахстан',
            },
            city: {
              id: 2079,
              country_id: 1894,
              country_code: 'kz',
              region_id: 2074,
              name: 'Петропавловск',
              full_name: 'Петропавловск, Северо-Казахстанская область, Казахстан',
              has_regions: false,
            },
            city_region: {
              id: 1,
              city_id: 4400,
              city_ad_id: 11,
              name: 'Академический',
              full_name: 'Академический, Юго-Западный',
            },
          },
          sport_category: 'novice',
        },
        sport_id: 5,
        external_id: '98317',
        external_url: '/comment/view/?entityType=TrackerData&entityId=1709569',
        created_at: '2024-01-31 10:33:59',
        updated_at: '2024-02-04 11:45:46',
        start_date: '2024-01-31 09:31:15',
        start_date_local: '2024-01-31 12:31:15',
        start_date_user: '2024-01-31 15:31:15',
        name: 'Ходьба в обед',
        description: '',
        distance: 5237.71,
        steps: 6905,
        total_elevation_gain: 12,
        average_heartrate: 0,
        moving_time: 3647,
        elev_high: 0,
        elev_low: 0,
        route:
          'wwcmJontwD???@A??B?D?J?HAFA@A?CAECCCEEGCG@EBGHGHEDEH]^EAEBEFEHEFEFCFEFBNqF[CEE?CAICGFEHEDCBEDE@GAGEEAGCC?E?GAEAEACCE?E@EBCBECECHF?@c@ImAqA?PANELSBKFGDEBI?MCEBKGEMck@c@g@NO@GDCBE@EBE?EAEAECECCAEACAEAGACCEGCK?M@K@I@K?M@K@KBM@KAK?P??jJopA@A@E@A@I?I?KAMAKAMAMAKAIAI?I?G@I?I@K?K@K@I@I@I@I?K@M@K@K@K@I@K?I@I?KNmB?G?I@I?K?I@M@K@K@I@K?I@E?K@I?M@I@I@K@K@I?K@K@I?I@K@I?K@M?I@I@KBI@G@I@I@I?K@K@I@K@K?I@K@I@I?I@I@K?G@M?K@K@K?I@K@K?I@I?I@I@I@I@K@K?I@K@I@I@K?I@K@G@I@I@GBEBA@A?B????c@_BAK?KAMCI?K?M?KAI?KAIAI?IAKAKAKAOAKoUqyBl@MLAA?GDGDGFE@G@E@G@EBGDGFEDEFEDEBE@EB????@??A???????A??????A@IEECE?E?ECECCAECECE@E?EDIDC@EDGDEDEDE@EJGDG?E@EDEFEDEHALALCJCFCDC@AFAHCLAFAHAFAF?FBLBJ?L?LAPAJCJAFCJCHGPEJ?LANAP?PAL?H?FA@CBCDCHCFAN?N@X?J?L@L?HBJ?J?L?L?JAL@LAJAJAJAJAJ?H?JALAH?JCLALCJAH@I@Gs@dGCPGfB@XwE~i@FLFNDNBL?H@RCJ@J@J@L?JCN@J@JAM?IkBxHAB?EAHXf@[nGBMDBBB@F?J?J?HAJAJAJAJAL?LANAL?LCLAJAJ?LALALAJ?JALAJ?J?LAJAJALALCNAJALALCLAJALAHCFEBEGGAGAEAGAECEEEE',
        is_manual: false,
        end_date_local: '2024-01-31 13:32:02',
        has_dupes: false,
        flagged: false,
        max_pace: '2:05',
        pace: '11:36',
        elapsed_time: 3647,
        max_standing_distance: 5237.71,
        attached: true,
        stood: true,
        standing_status: 'stood',
        image: 'https://dev2.alivebe.com/track/1709569/image/',
        files: [],
        likesCount: 0,
        commentsCount: 0,
        complaintCount: 0,
        liked: false,
        complained: false,
        activity_id: null,
        os: 'android',
      },
      member: {
        joined_at: '2023-09-12 11:37:30',
        qgroup: 1,
        team_id: 474,
        results: {
          '1': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '2': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '3': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '4': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '5': {
            steps: 54927,
            distance: 106753,
            moving_time: 91304,
            total_elevation_gain: 12,
          },
          '6': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '7': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '8': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '23': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '24': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '25': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '26': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '27': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '28': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '29': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '30': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '31': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '32': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '33': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '34': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '35': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '36': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          score: 160.1,
          steps: 54927,
          distance: 106753,
          moving_time: 91304,
          distanceForQGroup: 66546.5,
          total_elevation_gain: 12,
        },
      },
    },
    {
      event_id: 129,
      extra: {
        priority: 1,
        avg_pace_event: '1200',
        event_memberships: 8,
        cheater: false,
        checked: false,
        admin_comment_count: 0,
        too_fast: null,
        too_fast_limit: '',
        manual: false,
        gps: true,
        import_delay: false,
        edited: false,
      },
      standing: {
        distance: 0,
        ratio: 1,
        moving_time: 0,
        pace: null,
        score: '0',
        standing: {
          stood: false,
          status: 'auto_denied',
          message: null,
        },
        criteria: {
          distance: {
            min: 1000,
            aim: 1000,
            fact: 152.7,
            stood: false,
          },
          pace: {
            min: null,
            max: null,
            aim: null,
            fact: '24',
            stood: true,
          },
          has_route: true,
          is_not_manual: true,
          import_delay: {
            min: null,
            aim: null,
            fact: 1,
            stood: true,
          },
          dupe_check: true,
          time_of_day: {
            min: null,
            max: null,
            aim: null,
            fact: '14:54',
            stood: true,
          },
        },
      },
      track: {
        id: 1313854,
        tracker: {
          id: 10857,
          tracker: 'alivebe',
          created_at: '2022-06-10 09:12:23',
          updated_at: '2022-06-10 09:12:23',
          last_sync_time: '2024-02-04 11:45:46',
          last_error_id: null,
          enabled: true,
        },
        user: {
          id: 1697,
          first_name: 'Alexander',
          last_name: 'Ivanov',
          full_name: 'Alexander Ivanov',
          avatar:
            'https://dev2.alivebe.com/thumbnails/user/20230913/818fbf61cc5f7a4a1e0a2f846c90e317_160x160.jpg',
          last_online: '2024-02-04 11:56:50',
          age: 34,
          date_of_birth: '1989-11-07',
          gender: 'm',
          isFriend: false,
          friendRequest: false,
          rating: {
            place: 84,
            points: '308.64',
          },
          awardCount: 0,
          likeCount: 11,
          friendCount: 0,
          location: {
            country: {
              id: 1894,
              code: 'kz',
              name: 'Казахстан',
            },
            city: {
              id: 2079,
              country_id: 1894,
              country_code: 'kz',
              region_id: 2074,
              name: 'Петропавловск',
              full_name: 'Петропавловск, Северо-Казахстанская область, Казахстан',
              has_regions: false,
            },
            city_region: {
              id: 1,
              city_id: 4400,
              city_ad_id: 11,
              name: 'Академический',
              full_name: 'Академический, Юго-Западный',
            },
          },
          sport_category: 'novice',
        },
        sport_id: 3,
        external_id: '262',
        external_url: '/comment/view/?entityType=TrackerData&entityId=1313854',
        created_at: '2023-06-02 12:54:54',
        updated_at: '2024-02-04 11:45:46',
        start_date: '2023-06-02 11:54:03',
        start_date_local: '2023-06-02 14:54:03',
        start_date_user: '2023-06-02 17:54:03',
        name: 'Велозаезд в обед',
        description: '',
        distance: 152.67,
        steps: 0,
        total_elevation_gain: 2,
        average_heartrate: 0,
        moving_time: 23,
        elev_high: 0,
        elev_low: 0,
        route: 'm`srIau{bFBDDH?VEJDJBDFJBFBDFJBDDJBFT^HPLVR^HPR`@HN',
        is_manual: false,
        end_date_local: '2023-06-02 14:54:26',
        has_dupes: false,
        flagged: false,
        max_pace: '0',
        pace: '24',
        elapsed_time: 23,
        max_standing_distance: 152.67,
        attached: true,
        stood: false,
        standing_status: 'not_stood',
        image: 'https://dev2.alivebe.com/track/1313854/image/',
        files: [],
        likesCount: 0,
        commentsCount: 0,
        complaintCount: 0,
        liked: false,
        complained: false,
        activity_id: null,
        os: 'ios',
      },
      member: {
        joined_at: '2024-01-31 12:37:28',
        qgroup: 1,
        team_id: null,
        results: {
          '1': {
            steps: 1802697,
            distance: 2308353,
            moving_time: 6,
            total_elevation_gain: 46,
          },
          '2': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '3': {
            steps: 0,
            distance: 773921,
            moving_time: 2701,
            total_elevation_gain: 46,
          },
          '4': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '5': {
            steps: 1195675,
            distance: 1133768,
            moving_time: 297218,
            total_elevation_gain: 58,
          },
          '6': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '7': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '8': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '23': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '24': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '25': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '26': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '27': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '28': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '29': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '30': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '31': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '32': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '33': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '34': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '35': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '36': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          score: 9399.6,
          steps: 2998372,
          distance: 4216042,
          moving_time: 299925,
          distanceForQGroup: 15099,
          total_elevation_gain: 150,
        },
      },
    },
    {
      event_id: 129,
      extra: {
        priority: 1,
        avg_pace_event: '1200',
        event_memberships: 8,
        cheater: false,
        checked: false,
        admin_comment_count: 0,
        too_fast: null,
        too_fast_limit: '',
        manual: false,
        gps: true,
        import_delay: false,
        edited: false,
      },
      standing: {
        distance: 0,
        ratio: 1,
        moving_time: 0,
        pace: null,
        score: '0',
        standing: {
          stood: false,
          status: 'auto_denied',
          message: null,
        },
        criteria: {
          distance: {
            min: 1000,
            aim: 1000,
            fact: 773.9,
            stood: false,
          },
          pace: {
            min: null,
            max: null,
            aim: null,
            fact: '15',
            stood: true,
          },
          has_route: true,
          is_not_manual: true,
          import_delay: {
            min: null,
            aim: null,
            fact: 1,
            stood: true,
          },
          dupe_check: true,
          time_of_day: {
            min: null,
            max: null,
            aim: null,
            fact: '12:46',
            stood: true,
          },
        },
      },
      track: {
        id: 1313853,
        tracker: {
          id: 10857,
          tracker: 'alivebe',
          created_at: '2022-06-10 09:12:23',
          updated_at: '2022-06-10 09:12:23',
          last_sync_time: '2024-02-04 11:45:46',
          last_error_id: null,
          enabled: true,
        },
        user: {
          id: 1697,
          first_name: 'Alexander',
          last_name: 'Ivanov',
          full_name: 'Alexander Ivanov',
          avatar:
            'https://dev2.alivebe.com/thumbnails/user/20230913/818fbf61cc5f7a4a1e0a2f846c90e317_160x160.jpg',
          last_online: '2024-02-04 11:56:50',
          age: 34,
          date_of_birth: '1989-11-07',
          gender: 'm',
          isFriend: false,
          friendRequest: false,
          rating: {
            place: 84,
            points: '308.64',
          },
          awardCount: 0,
          likeCount: 11,
          friendCount: 0,
          location: {
            country: {
              id: 1894,
              code: 'kz',
              name: 'Казахстан',
            },
            city: {
              id: 2079,
              country_id: 1894,
              country_code: 'kz',
              region_id: 2074,
              name: 'Петропавловск',
              full_name: 'Петропавловск, Северо-Казахстанская область, Казахстан',
              has_regions: false,
            },
            city_region: {
              id: 1,
              city_id: 4400,
              city_ad_id: 11,
              name: 'Академический',
              full_name: 'Академический, Юго-Западный',
            },
          },
          sport_category: 'novice',
        },
        sport_id: 3,
        external_id: '261',
        external_url: '/comment/view/?entityType=TrackerData&entityId=1313853',
        created_at: '2023-06-02 10:51:33',
        updated_at: '2024-02-04 11:45:46',
        start_date: '2023-06-02 09:46:59',
        start_date_local: '2023-06-02 12:46:59',
        start_date_user: '2023-06-02 15:46:59',
        name: 'Велозаезд в обед',
        description: '',
        distance: 773.94,
        steps: 0,
        total_elevation_gain: 5,
        average_heartrate: 0,
        moving_time: 177,
        elev_high: 0,
        elev_low: 0,
        route:
          'c~rrIux{bFBFBD@PCDELCDGLADINCDGJADCDGLCDGJGJGMCECEGKCEGKCECEGKCGKQGKCEEKCECEOWKQCGGKCEGKAEGKCECEKEEJGLCDGLCDCFGMCEGKCEGMCECGEKCGGMAECEGMCEEMCEGMCEGOCECEKSEKCEGMCEGKCECGGKCEEMCECEGKCGGKCEGKCGAEGKCEGMCEKQCECGGKCEEKCEGKCGCEGKCEGKCECEGMCEGKCEGKCEEMCECEGKCEIKCECCIICCII~HpNyIcPIIGICCECGIECGICCIIGECCIEECIECCIGECCFEBE?ICEAIAEACAICEAIAEAICC?EA@N@H@P@FANE@CBIBEB',
        is_manual: false,
        end_date_local: '2023-06-02 12:49:56',
        has_dupes: false,
        flagged: false,
        max_pace: '0',
        pace: '15',
        elapsed_time: 177,
        max_standing_distance: 773.94,
        attached: true,
        stood: false,
        standing_status: 'not_stood',
        image: 'https://dev2.alivebe.com/track/1313853/image/',
        files: [],
        likesCount: 0,
        commentsCount: 0,
        complaintCount: 0,
        liked: false,
        complained: false,
        activity_id: null,
        os: 'ios',
      },
      member: {
        joined_at: '2024-01-31 12:37:28',
        qgroup: 1,
        team_id: null,
        results: {
          '1': {
            steps: 1802697,
            distance: 2308353,
            moving_time: 6,
            total_elevation_gain: 46,
          },
          '2': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '3': {
            steps: 0,
            distance: 773921,
            moving_time: 2701,
            total_elevation_gain: 46,
          },
          '4': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '5': {
            steps: 1195675,
            distance: 1133768,
            moving_time: 297218,
            total_elevation_gain: 58,
          },
          '6': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '7': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '8': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '23': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '24': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '25': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '26': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '27': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '28': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '29': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '30': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '31': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '32': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '33': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '34': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '35': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          '36': {
            steps: null,
            distance: null,
            moving_time: null,
            total_elevation_gain: null,
          },
          score: 9399.6,
          steps: 2998372,
          distance: 4216042,
          moving_time: 299925,
          distanceForQGroup: 15099,
          total_elevation_gain: 150,
        },
      },
    },
  ],
};
