export type TrackerDetails = {
  id: number;
  user_id: number;
  type_id: number;
  name: string;
  description: string;
  start_date: string;
  start_date_local: string;
  distance: number;
  elevation_gain: number;
  average_heartrate: number;
  moving_time: number;
  elapsed_time: number;
  max_speed: number;
  route: string;
  accuracy: string;
  steps: number;
  os: string;
  client_id: string;
  device_type: string;
  synced: boolean;
  created_at: string;
  updated_at: string;
  points?: PointsEntity[] | null;
};
export type PointsEntity = {
  id: number;
  time: string;
  distance: number;
  lat: number;
  lng: number;
  altitude: number;
  speed: number;
  pace: string;
  steps: number;
  accuracy: number;
  segment: number;
};
